### ISSUE TITLE
cannot fine fea

### ISSUE THREAD

**Issue by jjxx2** [VahanaOpenSource/vtol_sizing#5]
C:\Users\soren\OneDrive\Desktop\vtol_sizing-master\cases\Alpha>set PYTHONPATH=C:\path\to\fea

C:\Users\soren\OneDrive\Desktop\vtol_sizing-master\cases\Alpha>C:\Users\soren\AppData\Local\Programs\Python\Python312\python.exe xrun.py
Traceback (most recent call last):
  File "C:\Users\soren\OneDrive\Desktop\vtol_sizing-master\cases\Alpha\xrun.py", line 36, in <module>
    from hydraInterface    import hydraInterface
  File "C:\Users\soren\OneDrive\Desktop\vtol_sizing-master\cases\Alpha\../../src/Python/Stage_0\hydraInterface.py", line 32, in <module>
    import FEA_class
  File "C:\Users\soren\OneDrive\Desktop\vtol_sizing-master\cases\Alpha\../../src/Python/Stage_3\FEA_class.py", line 11, in <module>
    import fea
ModuleNotFoundError: No module named 'fea'

**Comment by nenanth** [comment]
hi @jjxx2 : you may need to build the fortran part of the sizing code. Please run the cmake script
